# Generated by Django 3.0.4 on 2020-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send_weeks',
            options={'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterField(
            model_name='userlist',
            name='ul_mailing_time',
            field=models.CharField(max_length=2, null=True, verbose_name='Время рассылки'),
        ),
    ]
