# Generated by Django 3.0.4 on 2020-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlist',
            fields=[
                ('el_id', models.AutoField(primary_key=True, serialize=False)),
                ('el_title', models.CharField(max_length=50)),
                ('el_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('el_date', models.DateTimeField()),
                ('el_time', models.TimeField()),
                ('el_link', models.CharField(max_length=100)),
                ('el_chk_active', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placelist',
            fields=[
                ('pl_id', models.AutoField(primary_key=True, serialize=False)),
                ('pl_city', models.CharField(max_length=30)),
                ('pl_str_name', models.CharField(max_length=30)),
                ('pl_house_num', models.IntegerField()),
                ('pl_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pl_place_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taglist',
            fields=[
                ('tl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tl_title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('ul_id', models.AutoField(primary_key=True, serialize=False)),
                ('ul_login', models.CharField(max_length=20)),
                ('ul_password', models.CharField(max_length=20)),
                ('ul_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ul_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('ul_secondname', models.CharField(blank=True, max_length=20, null=True)),
                ('ul_email', models.CharField(max_length=30)),
                ('ul_linkvkmessage', models.CharField(blank=True, max_length=30, null=True)),
                ('ul_linktgmessage', models.CharField(blank=True, max_length=30, null=True)),
                ('ul_chk_mailing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usertaglist',
            fields=[
                ('utl_id', models.AutoField(primary_key=True, serialize=False)),
                ('utl_id_tag', models.ForeignKey(db_column='utl_id_tag', on_delete=django.db.models.deletion.DO_NOTHING, to='mefi_app.Taglist')),
                ('utl_id_user', models.ForeignKey(db_column='utl_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='mefi_app.Userlist')),
            ],
        ),
        migrations.CreateModel(
            name='Eventtaglist',
            fields=[
                ('etl_id', models.AutoField(primary_key=True, serialize=False)),
                ('etl_id_event', models.ForeignKey(db_column='etl_id_event', on_delete=django.db.models.deletion.DO_NOTHING, to='mefi_app.Eventlist')),
                ('etl_id_tag', models.ForeignKey(db_column='etl_id_tag', on_delete=django.db.models.deletion.DO_NOTHING, to='mefi_app.Taglist')),
            ],
        ),
        migrations.AddField(
            model_name='eventlist',
            name='el_id_place',
            field=models.ForeignKey(db_column='el_id_place', on_delete=django.db.models.deletion.DO_NOTHING, to='mefi_app.Placelist'),
        ),
    ]
